#!/usr/bin/env bash
# Initialize Shitty Swarm Manager for a repository
# Creates .swarm/ directory with config, hooks, and database connection

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
SWARM_DIR="$REPO_ROOT/.swarm"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🐝 Initializing Shitty Swarm Manager...${NC}"
echo ""

# Check if already initialized
if [[ -d "$SWARM_DIR" ]]; then
	echo -e "${YELLOW}⚠️  Already initialized at $SWARM_DIR${NC}"
	echo "   Run 'swarm reinit' to reset or 'swarm config' to update"
	exit 0
fi

# Create .swarm directory
mkdir -p "$SWARM_DIR"

# Get repository info
REPO_NAME=$(basename "$REPO_ROOT")
REPO_ID=$(git remote get-url origin 2>/dev/null || echo "$REPO_NAME")
GIT_PATH=$(pwd)

# Create config.toml
cat >"$SWARM_DIR/config.toml" <<EOF
# Shitty Swarm Manager Configuration
# Auto-generated by 'swarm init'

[repo]
id = "$REPO_ID"
name = "$REPO_NAME"
path = "$GIT_PATH"

[database]
# PostgreSQL connection
host = "localhost"
port = 5432
database = "swarm_db"
user = "swarm"
password = "swarm"

[swarm]
# Number of agents for this repo
max_agents = 12
max_implementation_attempts = 3
claim_label = "p0"

[agent]
# Default agent command
command = "claude"
auto_spawn = false

[monitoring]
# Dashboard settings
refresh_ms = 1000
show_all_repos = false
EOF

echo -e "${GREEN}✅ Created $SWARM_DIR/config.toml${NC}"

# Create .swarmignore (like .gitignore but for swarm)
cat >"$SWARM_DIR/.swarmignore" <<EOF
# Shitty Swarm Manager - Ignore patterns
*.log
.cache/
temp/
EOF

echo -e "${GREEN}✅ Created $SWARM_DIR/.swarmignore${NC}"

# Check PostgreSQL connectivity
echo ""
echo -e "${BLUE}🔍 Checking PostgreSQL...${NC}"

if ! command -v psql &>/dev/null; then
	echo -e "${YELLOW}⚠️  psql not found. Install PostgreSQL client:${NC}"
	echo "   sudo apt install postgresql-client  # Debian/Ubuntu"
	echo "   brew install libpq                  # macOS"
	exit 1
fi

# Test connection
if psql -h localhost -U swarm -d swarm_db -c "SELECT 1" &>/dev/null; then
	echo -e "${GREEN}✅ PostgreSQL connection successful${NC}"
else
	echo -e "${YELLOW}⚠️  PostgreSQL not accessible${NC}"
	echo ""
	echo "Start PostgreSQL:"
	echo "   # Docker (recommended)"
	echo "   docker run -d --name swarm-db -p 5432:5432 -e POSTGRES_USER=swarm -e POSTGRES_PASSWORD=swarm -e POSTGRES_DB=swarm_db postgres:16"
	echo ""
	echo "   # Or use existing PostgreSQL"
	echo "   createdb swarm_db"
	echo "   createuser -P swarm  # Set password to 'swarm'"
	echo ""
	echo "   # Then initialize schema:"
	echo "   psql -h localhost -U swarm -d swarm_db -f schema.sql"
fi

# Create hooks directory
mkdir -p "$SWARM_DIR/hooks"

# Register repo in database (if accessible)
if psql -h localhost -U swarm -d swarm_db -c "SELECT 1" &>/dev/null; then
	echo ""
	echo -e "${BLUE}📝 Registering repository in database...${NC}"

	psql -h localhost -U swarm -d swarm_db -c "
        INSERT INTO repos (repo_id, name, path, git_remote)
        VALUES ('$REPO_ID', '$REPO_NAME', '$GIT_PATH', '$REPO_ID')
        ON CONFLICT (repo_id) DO UPDATE SET last_active_at = NOW();
    " 2>/dev/null && echo -e "${GREEN}✅ Repository registered${NC}" || echo -e "${YELLOW}⚠️  Schema not initialized. Run: psql -h localhost -U swarm -d swarm_db -f schema.sql${NC}"
fi

echo ""
echo -e "${GREEN}🎉 Shitty Swarm Manager initialized!${NC}"
echo ""
echo "Next steps:"
echo "   1. Start PostgreSQL (if not running)"
echo "   2. Load schema: psql -h localhost -U swarm -d swarm_db -f schema.sql"
echo "   3. Register agents: swarm register 12"
echo "   4. Start monitoring: swarm dashboard"
echo ""
echo "Configuration: $SWARM_DIR/config.toml"
echo "Database:      postgresql://swarm@localhost:5432/swarm_db"
